server {
    listen 443 ssl;
    server_name app.vopumanagement.site;

    ssl_certificate /etc/ssl/cloudflare/cert.pem;
    ssl_certificate_key /etc/ssl/cloudflare/key.pem;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}

server {
    listen 80;
    server_name app.vopumanagement.site;
    return 301 https://$host$request_uri;
}